language: node_js
node_js:
- "--lts"
before_script:
- npm install -g harp
- chmod +x ./deploy.sh
script: true
after_success: "./deploy.sh"
env:
  global:
    secure: gAhW4vC2iMejPzIXssmsGihISyHSn9ZiFK2S4xoz/q4qcM9LBQlc80LPs4k3Ce9xvGCtm0Rawhz0oMUN0JhyVMN/7RGrDBbPtBkS1jBL+fjfz10qqFuGcPD5eronH1ugjwEjKKlkj46/BxwhAYbou0/lhhvmnFVWoD6u7maG5MKjl91FzT3SfoSvlPs9BPAHj8LMvWAUrB0vBvwPE4nuR2dSISf9wqxDMg7rOFKhSZGf6NWpz4RGl7iaClMzBrrIFDFlNYhxmSmwlOl/BmP0y0gVstUGl0KiWACY2DF+KaDOFbgewdPsG0Zz61ki7uoFaU3Z9KVKfSnVpaz/6RakJKgOFXwqavvZfpn5yMU9s7blHJrYklAUial6a1vYICb6CacS73v3TyWQuVSiqk9knZOVUkn+v6Pe26Txvzrz8FQhUjd7ua87nHu44fnsW/GMBRazoqySO3SkJ0we00D93j0x8G3LWeW8Vtqs+qUixRADtld7D2FjPPRNM6ZKL6JGKjC0qhhDE2hidLkd1xiY7VXuBnm4xKeEsjxxgRRK/9CRfQv1fAxEWWlz7hnYOzsLT31HY1YFMMHfftQxH9SpX1HgHE2cCfSx/AbMMWMvmLVnuy65wgihb/79jIMtbTNtCCV1duOZ/dyLrt5I1tOf+PwKjpJMhUnXDe1JEBNQwcE=
notifications:
  slack:
    rooms:
      secure: Ysx5dEn96Z18rsvDkeNp7ZPYaSSA0eQ2GuNKAE5VaPH64RV3i62KCtd3+zELclb5oCBJceK6F4sj78v87EZ+vVDM+TmreC+hk+DgJOBWURpvzirMjInNQ+YddoiWQzyRBvZI2faFb3V1kC5Xz+kHYva7ctWgfQLCPyTT7BJBDRRy/3LPcJvotPuW4vznf+UUxiBNu+zrigllfeaXeuZ4xfBE/mHBHATcyGOX/4cJ6++hjuHSKJ3xpODa5a5BruJ0VaaTBfNjoC/yHyumBMLcLQp4gSPYE8mGbYlBn3ks2ITI+LqP6dWwa5XKsDg+ZazN+VuGTs/6DfzeAgjpiuUDB8SEakco/MRqM040e7Mj2E8vlvMl9dzojkHihTsz38tsaR+u8Pjmn3zf1o/481vGD0KxR70WeURfnGX0SXqy7Cg/HcF0DHqd+7UOZtrWCUzZqqQIyWsRtzIw38pnrDcAxeOTeJIvlLM16zzgd6tT+0oE+TCvTQ/HBkgljzwUttkIUMmZjljypSTCFuGAMEQ5Iqhl2fYd5Ty2Yewf5qEvo/S4AIh4WW8EN3v/qODk1bpLdftHwzuJSln/zz48n8BROI9MPlwsG9kKcKiDnT/Vk2AR5Prdskz9jRTe5/91Kt6PY3AI7IpErNO/GZoVobg9n27V1QGGmufOTdX1CLLhi9M=
