language: node_js
node_js:
- "--lts"
before_script:
- npm install -g harp
- chmod +x ./deploy.sh
script: true
after_success: "./deploy.sh"
env:
  global:
    secure: VPc4RqqXFud8t5il9ThKuuMSIVcXotQjMJzZlxnvmr/xzazp+QORgNAj56nmn1MuRVSAAdNtFKUIwrSOCRCrJahMcHnIkFgtJufsUG93S+UsbRBWLDXQ3uFGNhSYgk+13vsyFwtfqub+qfvGeDraQ9sa32A4pDNDzgPWnEHPpXxGfwnpkdoiFvX/XFgjO6srN1eMPe/UEi71fI2gk61EwFQjygnQy2XQiL2PYX+FFDFA4Yi6bTNZ1JZjvAoayiNhbVffJ4hm23czZ9kzz5d4Unzm2ASloqz7hO1mr31EvgsdliQj1KAHrjKtDiEPNchzCGwvrLtIo8Px3m63eWAY1hW+t6YhHE22S5pUipo1mR1Eeny1NZObyxdJX9+YjylqKtAjqMO/IZwTISAjZDvDpjAz2BDRrlL83/LgIOJDEbWbnfiI7AVx0ZJXwHXN4k+8sMcKKOq73P+aNwDs8EbADiT8N4y0rIq8L18KCPbIWROAy7IGgbYb2tVbAVnyxYqufq5YGn1rauFA99QOCLoskYuP4+0OWcaCI/YBbDeK0MGr7zAGGlD6R1xBiucy7Y46VzPi/CmsWecs4ekj9cY9a5ijbBEipHjMUnGsz6h6HK54XjyorMZQPqxFcRzEJzmS7GQS5r+3+ZcemB44Y02SP2qxG/O2fp5ts+6UawhDkGg=
notifications:
  slack:
    rooms:
      secure: Ysx5dEn96Z18rsvDkeNp7ZPYaSSA0eQ2GuNKAE5VaPH64RV3i62KCtd3+zELclb5oCBJceK6F4sj78v87EZ+vVDM+TmreC+hk+DgJOBWURpvzirMjInNQ+YddoiWQzyRBvZI2faFb3V1kC5Xz+kHYva7ctWgfQLCPyTT7BJBDRRy/3LPcJvotPuW4vznf+UUxiBNu+zrigllfeaXeuZ4xfBE/mHBHATcyGOX/4cJ6++hjuHSKJ3xpODa5a5BruJ0VaaTBfNjoC/yHyumBMLcLQp4gSPYE8mGbYlBn3ks2ITI+LqP6dWwa5XKsDg+ZazN+VuGTs/6DfzeAgjpiuUDB8SEakco/MRqM040e7Mj2E8vlvMl9dzojkHihTsz38tsaR+u8Pjmn3zf1o/481vGD0KxR70WeURfnGX0SXqy7Cg/HcF0DHqd+7UOZtrWCUzZqqQIyWsRtzIw38pnrDcAxeOTeJIvlLM16zzgd6tT+0oE+TCvTQ/HBkgljzwUttkIUMmZjljypSTCFuGAMEQ5Iqhl2fYd5Ty2Yewf5qEvo/S4AIh4WW8EN3v/qODk1bpLdftHwzuJSln/zz48n8BROI9MPlwsG9kKcKiDnT/Vk2AR5Prdskz9jRTe5/91Kt6PY3AI7IpErNO/GZoVobg9n27V1QGGmufOTdX1CLLhi9M=
